[package]
name = "mirror_plugin"
version = "0.1.0"
edition = "2021"
authors = ["mirrorganger"]

[lib]
crate-type = ["cdylib"]

[dependencies]
nih_plug = { git = "https://github.com/robbert-vdh/nih-plug.git", features = ["assert_process_allocs"] }
parking_lot = "0.12"
